/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package pt.isel

import pt.isel.sample.Student
import pt.isel.sample.toStudent
import java.io.File
import java.nio.file.Files
import kotlin.io.path.toPath
import kotlin.streams.asSequence
import kotlin.test.Test
import kotlin.test.assertEquals

class `Queries4vs3-lazy-vs-eager` {
    private val lae2022uri = ClassLoader.getSystemClassLoader().getResource("lae2022.txt").toURI()


    @Test fun `EAGER select first surname of a Student`() {
        var count = 0
        val actual = File(lae2022uri)
            .readLines()
            .parseCsv(';')
            .map { count++; it.toObject<Student>() }
            .map { count++; it.name.split(" ").last() }
            .iterator().next() // First item
        assertEquals("Costa", actual)
        assertEquals( 220, count)
    }

    @Test fun `LAZY select first surname of a Student`() {
        var count = 0
        val actual = File(lae2022uri)
            .readLines()
            .parseCsv(';')
            .convertLazy { count++; it.toObject<Student>() }
            .convertLazy { count++; it.name.split(" ").last() }
            .iterator().next() // First item
        assertEquals("Costa", actual)
        assertEquals(2, count)
    }

    @Test fun `LAZY with Sequence select first surname of a Student`() {
        var count = 0
        val actual = Files
            .lines(lae2022uri.toPath())
            .asSequence()
            .parseCsv(';')
            .asSequence()
            .map { count++; it.toObject<Student>() }
            .map { count++; it.name.split(" ").last() }
            .iterator().next() // First item
        assertEquals("Costa", actual)
        assertEquals(2, count)
    }
}
